### ISSUE TITLE
production.ERROR

### ISSUE THREAD

**Issue by northeaster** [FriendsOfFlarum/upload#215]
```
[2020-05-20 00:36:43] production.ERROR: FoF\Upload\Exceptions\InvalidDownloadException: Client error: `GET https://forum.sourceturk.net/assets/files/2020-05-18/1589809931-608950-dc-round-info.zip` resulted in a `403 Forbidden` response:
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class (truncated...)
 in /var/www/sourceturk/flarum/vendor/fof/upload/src/Downloader/DefaultDownloader.php:49
Stack trace:
#0 /var/www/sourceturk/flarum/vendor/fof/upload/src/Commands/DownloadHandler.php(82): FoF\Upload\Downloader\DefaultDownloader->download()
#1 /var/www/sourceturk/flarum/vendor/illuminate/bus/Dispatcher.php(90): FoF\Upload\Commands\DownloadHandler->handle()
#2 /var/www/sourceturk/flarum/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#3 /var/www/sourceturk/flarum/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#4 /var/www/sourceturk/flarum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#5 /var/www/sourceturk/flarum/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow()
#6 /var/www/sourceturk/flarum/vendor/fof/upload/src/Api/Controllers/DownloadController.php(64): Illuminate\Bus\Dispatcher->dispatch()
#7 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): FoF\Upload\Api\Controllers\DownloadController->handle()
#8 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#9 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#10 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#11 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#12 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#13 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#14 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle()
#15 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#16 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#17 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#18 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#19 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#20 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#21 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#22 /var/www/sourceturk/flarum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#23 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#24 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#25 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#26 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#27 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#28 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#29 /var/www/sourceturk/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#30 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#31 /var/www/sourceturk/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#32 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#33 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#34 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#35 /var/www/sourceturk/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#36 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#37 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#38 /var/www/sourceturk/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#39 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#40 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#41 /var/www/sourceturk/flarum/public/index.php(26): Flarum\Http\Server->listen()
#42 {main}  
```

**Comment by northeaster** [comment]
```
# php flarum info
Flarum core 0.1.0-beta.13
PHP version: 7.4.6
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imap, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+----------------------------------+-------------------+--------+
| Flarum Extensions                |                   |        |
+----------------------------------+-------------------+--------+
| ID                               | Version           | Commit |
+----------------------------------+-------------------+--------+
| flarum-approval                  | v0.1.0-beta.13    |        |
| flarum-flags                     | v0.1.0-beta.13    |        |
| flarum-likes                     | v0.1.0-beta.13    |        |
| flarum-lock                      | v0.1.0-beta.13    |        |
| flarum-markdown                  | v0.1.0-beta.13    |        |
| flarum-mentions                  | v0.1.0-beta.13    |        |
| flarum-sticky                    | v0.1.0-beta.13    |        |
| flarum-subscriptions             | v0.1.0-beta.13    |        |
| flarum-suspend                   | v0.1.0-beta.13    |        |
| flarum-tags                      | v0.1.0-beta.13    |        |
| flarum-emoji                     | v0.1.0-beta.13    |        |
| flarum-lang-english              | v0.1.0-beta.13    |        |
| fof-terms                        | 0.4.2             |        |
| fof-transliterator               | 0.2.0             |        |
| fof-pages                        | 0.4.0             |        |
| fof-user-directory               | 0.3.4             |        |
| fof-merge-discussions            | 0.3.3             |        |
| flagrow-ads                      | 0.2.4             |        |
| fof-best-answer                  | 0.1.7             |        |
| fof-drafts                       | 0.1.5             |        |
| fof-links                        | 0.3.0             |        |
| fof-user-bio                     | 0.1.3             |        |
| v17development-seo               | 1.2               |        |
| fof-follow-tags                  | 0.3.4             |        |
| fof-socialprofile                | 0.1.2             |        |
| fof-subscribed                   | 0.2.3             |        |
| fof-formatting                   | 0.1.4             |        |
| flarum-auth-github               | v0.1.0-beta.13    |        |
| fof-recaptcha                    | 0.1.2             |        |
| saleksin-auth-google             | v0.1.0-beta.8.0.3 |        |
| flarum-auth-facebook             | v0.1.0-beta.13    |        |
| fof-auth-discord                 | 0.1.3             |        |
| flarum-auth-twitter              | v0.1.0-beta.13    |        |
| fof-polls                        | 0.1.2             |        |
| fof-byobu                        | 0.5.0             |        |
| flagrow-analytics                | 0.8.0             |        |
| fof-geoip                        | 0.1.7             |        |
| flarum-bbcode                    | v0.1.0-beta.12    |        |
| fof-upload                       | 0.9.1             |        |
| flarum-pusher                    | v0.1.0-beta.13    |        |
| isaced-email-verification-switch | 0.1.3             |        |
| fof-realtimedate                 | 0.1.2             |        |
| tolgaaaltas-turkish              | 0.13.2            |        |
| tolgaaaltas-lang-turkish         | 0.13.0            |        |
| fof-profile-image-crop           | 0.1.1             |        |
| flarum-statistics                | v0.1.0-beta.13    |        |
| clarkwinkelmann-circle-groups    | 0.2.1             |        |
| therealsujitk-gifs               | v1.4.8            |        |
| zerosonesfun-hashtags            | 2.0.1             |        |
| askvortsov-moderator-warnings    | v0.1.6            |        |
| fof-spamblock                    | 0.2.2             |        |
| fof-share-social                 | 0.1.2             |        |
| nomiscz-auth-steam               | v0.1.7            |        |
| the-turk-password-strength       | 0.1.3             |        |
| therealsujitk-show-password      | v1.0.3            |        |
| fof-nightmode                    | 0.4.0             |        |
| the-turk-diff                    | 1.0.7             |        |
| bokt-redis                       | 0.1.0             |        |
| fof-sitemap                      | 0.4.0             |        |
| the-turk-extended-appearance     | 0.1.1             |        |
| askvortsov-categories            | v1.0.1            |        |
+----------------------------------+-------------------+--------+
Base URL: https://forum.sourceturk.net
Installation path: /var/www/sourceturk/flarum
Debug mode: off
```

**Comment by luceos** [comment]
For some reason it cannot access the file in assets/files; did you change anything in your htaccess or server configuration that might have done that?

**Comment by northeaster** [comment]
This is my nginx settings. Is there a problem with the settings?

```
server {
    listen 80;
    listen [::]:80;
    root /var/www/sourceturk/flarum/public;
    index index.php index.html index.htm;
    server_name forum.sourceturk.net;
	
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
	
	location ~ /\.
	{
		deny all;
	}

	location = /favicon.ico
	{
		log_not_found off;
		access_log off;
	}

	location = /robots.txt
	{
		log_not_found off;
		access_log off;
		allow all;
	}
	
	location = /sitemap.xml
	{
		try_files $uri $uri/ /index.php?$query_string;
	}

    include /var/www/sourceturk/flarum/.nginx.conf;
	
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	ssl on;
	ssl_certificate         /etc/ssl/certs/cert.pem;
	ssl_certificate_key     /etc/ssl/private/key.pem;
	ssl_client_certificate	/etc/ssl/certs/cloudflare.crt;
}

```

**Comment by northeaster** [comment]
The file does not download when cloudflare js chal is open. The problem was solved when I closed js chal.
How can we set the file download when js chal is open?

**Comment by clarkwinkelmann** [comment]
do you mean javascript challenge ?

Ideally if you're using Cloudflare, you should setup your host in a way that the hostname resolves to localhost, and make sure your HTTPS certificate validates locally by being public or with a local key chain. That way the internal proxying can be done locally without your server making requests to itself through Cloudflare.

**Comment by clarkwinkelmann** [comment]
Closing this because of inactivity. Feel free to re-open if you still require assistance. Thanks.
