### ISSUE TITLE
Failed to open extended function

### ISSUE THREAD

**Issue by peter100u** [FriendsOfFlarum/upload#302]
## Bug Report

**Current Behavior**
I use the latest version, composer require fof / upload, which has been installed successfully, but when I start it in the background, I report an error. The content is that the index is too long. Here is my error log

**log**
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'processingfof_upload_files_actor_id_hide_from_media_manager_index' is too long in /www/wwwroot/processing.love/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /www/wwwroot/processing.love/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute()
#1 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(492): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(696): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback()
#4 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(493): Illuminate\Database\Connection->run()
#5 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#6 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#7 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(212): Illuminate\Database\Schema\Builder->build()
#8 /www/wwwroot/processing.love/vendor/fof/upload/migrations/2021_09_30_000000_add_index_actor_id_and_hide_media.php(20): Illuminate\Database\Schema\Builder->table()
#9 [internal function]: Illuminate\Filesystem\Filesystem::{closure}()
#10 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(202): call_user_func()
#11 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(133): Flarum\Database\Migrator->runClosureMigration()
#12 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(116): Flarum\Database\Migrator->runUp()
#13 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(90): Flarum\Database\Migrator->runMigrationList()
#14 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Extension.php(503): Flarum\Database\Migrator->run()
#15 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(311): Flarum\Extension\Extension->migrate()
#16 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(182): Flarum\Extension\ExtensionManager->migrate()
#17 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Command/ToggleExtensionHandler.php(36): Flarum\Extension\ExtensionManager->enable()
#18 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Extension\Command\ToggleExtensionHandler->handle()
#19 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#20 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#22 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#23 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(43): Illuminate\Bus\Dispatcher->dispatch()
#24 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\UpdateExtensionController->handle()
#25 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#26 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#27 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#28 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process()
#29 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#30 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#31 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#32 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#33 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#34 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#35 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle()
#36 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#37 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#38 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#39 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#40 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#41 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#42 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#43 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#44 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process()
#45 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#46 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#47 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#48 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#49 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#50 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#51 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#52 /www/wwwroot/processing.love/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#53 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#54 /www/wwwroot/processing.love/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#55 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#56 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#57 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#58 /www/wwwroot/processing.love/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#59 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#60 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#61 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#62 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#63 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#64 /www/wwwroot/processing.love/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#65 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#66 /www/wwwroot/processing.love/public/index.php(26): Flarum\Http\Server->listen()
#67 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'processingfof_upload_files_actor_id_hide_from_media_manager_index' is too long in /www/wwwroot/processing.love/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /www/wwwroot/processing.love/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(492): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(696): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback()
#4 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(493): Illuminate\Database\Connection->run()
#5 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#6 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#7 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(212): Illuminate\Database\Schema\Builder->build()
#8 /www/wwwroot/processing.love/vendor/fof/upload/migrations/2021_09_30_000000_add_index_actor_id_and_hide_media.php(20): Illuminate\Database\Schema\Builder->table()
#9 [internal function]: Illuminate\Filesystem\Filesystem::{closure}()
#10 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(202): call_user_func()
#11 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(133): Flarum\Database\Migrator->runClosureMigration()
#12 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(116): Flarum\Database\Migrator->runUp()
#13 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(90): Flarum\Database\Migrator->runMigrationList()
#14 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Extension.php(503): Flarum\Database\Migrator->run()
#15 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(311): Flarum\Extension\Extension->migrate()
#16 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(182): Flarum\Extension\ExtensionManager->migrate()
#17 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Command/ToggleExtensionHandler.php(36): Flarum\Extension\ExtensionManager->enable()
#18 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Extension\Command\ToggleExtensionHandler->handle()
#19 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#20 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#22 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#23 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(43): Illuminate\Bus\Dispatcher->dispatch()
#24 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\UpdateExtensionController->handle()
#25 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#26 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#27 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#28 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process()
#29 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#30 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#31 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#32 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#33 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#34 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#35 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle()
#36 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#37 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#38 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#39 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#40 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#41 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#42 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#43 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#44 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process()
#45 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#46 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#47 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#48 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#49 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#50 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#51 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#52 /www/wwwroot/processing.love/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#53 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#54 /www/wwwroot/processing.love/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#55 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#56 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#57 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#58 /www/wwwroot/processing.love/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#59 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#60 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#61 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#62 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#63 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#64 /www/wwwroot/processing.love/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#65 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#66 /www/wwwroot/processing.love/public/index.php(26): Flarum\Http\Server->listen()
#67 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'processingfof_upload_files_actor_id_hide_from_media_manager_index' is too long (SQL: alter table `processingfof_upload_files` add index `processingfof_upload_files_actor_id_hide_from_media_manager_index`(`actor_id`, `hide_from_media_manager`)) in /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php:703
Stack trace:
#0 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(663): Illuminate\Database\Connection->runQueryCallback()
#1 /www/wwwroot/processing.love/vendor/illuminate/database/Connection.php(493): Illuminate\Database\Connection->run()
#2 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#3 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#4 /www/wwwroot/processing.love/vendor/illuminate/database/Schema/Builder.php(212): Illuminate\Database\Schema\Builder->build()
#5 /www/wwwroot/processing.love/vendor/fof/upload/migrations/2021_09_30_000000_add_index_actor_id_and_hide_media.php(20): Illuminate\Database\Schema\Builder->table()
#6 [internal function]: Illuminate\Filesystem\Filesystem::{closure}()
#7 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(202): call_user_func()
#8 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(133): Flarum\Database\Migrator->runClosureMigration()
#9 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(116): Flarum\Database\Migrator->runUp()
#10 /www/wwwroot/processing.love/vendor/flarum/core/src/Database/Migrator.php(90): Flarum\Database\Migrator->runMigrationList()
#11 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Extension.php(503): Flarum\Database\Migrator->run()
#12 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(311): Flarum\Extension\Extension->migrate()
#13 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/ExtensionManager.php(182): Flarum\Extension\ExtensionManager->migrate()
#14 /www/wwwroot/processing.love/vendor/flarum/core/src/Extension/Command/ToggleExtensionHandler.php(36): Flarum\Extension\ExtensionManager->enable()
#15 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Extension\Command\ToggleExtensionHandler->handle()
#16 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#17 /www/wwwroot/processing.love/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#19 /www/wwwroot/processing.love/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#20 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(43): Illuminate\Bus\Dispatcher->dispatch()
#21 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\UpdateExtensionController->handle()
#22 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#23 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process()
#24 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#25 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process()
#26 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#27 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process()
#28 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#29 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process()
#30 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#31 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process()
#32 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle()
#33 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#34 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#35 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process()
#36 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#37 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process()
#38 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#39 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process()
#40 /www/wwwroot/processing.love/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#41 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process()
#42 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#43 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process()
#44 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#45 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process()
#46 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#47 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process()
#48 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#49 /www/wwwroot/processing.love/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#50 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process()
#51 /www/wwwroot/processing.love/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#52 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process()
#53 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#54 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process()
#55 /www/wwwroot/processing.love/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#56 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process()
#57 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#58 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process()
#59 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle()
#60 /www/wwwroot/processing.love/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process()
#61 /www/wwwroot/processing.love/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#62 /www/wwwroot/processing.love/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#63 /www/wwwroot/processing.love/public/index.php(26): Flarum\Http\Server->listen()
#64 {main}
```

**Environment**
- Flarum version: last
- Extension version: last
- Website URL: https://www.processing.love/
- Webserver: [apache, nginx/1.20.1]
- PHP version: PHP: 7.4.24
- Browser: [last]
-  mysql: [5.7.34]

**Comment by clarkwinkelmann** [comment]
This is because your database table prefix causes the index name (looks to be `processing`) to become too long.

Unfortunately there's no easy solution built into Flarum to handle this situation. The easiest would be to not use any table prefix if you can avoid it, but this might require editing your database if your forum is already in production.

You might be able to manually create/rename the index whose name is too long, and manually create the entry in the `migrations` table, but this require a bit of analysis of the migration files to know what has to be created by hand.

If you're able to re-install Flarum without a prefix or with a shorter prefix (max 3 characters ideally) the problem shouldn't happen.
