### ISSUE TITLE
Media Manager errors showing no media and refuse to close

### ISSUE THREAD

**Issue by eddiewebb** [FriendsOfFlarum/upload#408]
## Bug Report

**Current Behavior**
Media Manager comes up empty and wont close.  COnsole shows lots of errors.  Same behavior on User Profile 'my media' page

**Steps to Reproduce**
1. Edit or add a new post
2. Click "Media Manager" upload

OR

1. Visit your profile
2. Click "My Media" tab

**Expected Behavior**
See photos I have uploaded in past.

**Screenshots**

![https://ibb.co/d2p0Yxk](https://i.ibb.co/cF8cnV2/Screenshot-2024-10-14-at-7-42-40-PM.png)
![https://ibb.co/xSCZXCZ](https://i.ibb.co/WWxCGxC/Screenshot-2024-10-14-at-7-42-35-PM.png)

**Environment**

Flarum: 1.8.5
PHP: 8.3.12
MySQL: 10.6.18-MariaDB
FOF Upload: 1.5.5

```
FileListState.ts:81 TypeError: t.canViewInfo is not a function
    at i.actionItems (DisplayFile.tsx:118:10)
    at i.view (DisplayFile.tsx:81:49)
    at Function.a (render.js:30:16)
    at render.js:155:45
    at render.js:160:3
    at c (render.js:66:8)
    at l (render.js:50:5)
    at render.js:134:5
    at c (render.js:63:14)
    at l (render.js:50:5)
Composer.js:86 TypeError: Cannot read properties of undefined (reading 'onbeforeupdate')
    at render.js:929:60
    at p (render.js:407:8)
    at f (render.js:302:11)
    at render.js:477:5
    at p (render.js:416:15)
    at f (render.js:315:21)
    at render.js:444:3
    at p (render.js:415:16)
    at f (render.js:302:11)
    at render.js:477:5
﻿

```

```
Flarum core: 1.8.5
PHP version: 8.3.12
MySQL version: 10.6.18-MariaDB-0ubuntu0.22.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+-------------------------------------+------------+--------+
| Flarum Extensions                   |            |        |
+-------------------------------------+------------+--------+
| ID                                  | Version    | Commit |
+-------------------------------------+------------+--------+
| flarum-flags                        | v1.8.0     |        |
| flarum-tags                         | v1.8.1     |        |
| flarum-approval                     | v1.8.1     |        |
| fof-pages                           | 1.0.8      |        |
| flarum-suspend                      | v1.8.1     |        |
| flarum-mentions                     | v1.8.3     |        |
| flarum-subscriptions                | v1.8.0     |        |
| fof-upload                          | 1.5.5      |        |
| fof-sitemap                         | 2.2.1      |        |
| flarum-likes                        | v1.8.0     |        |
| fof-user-directory                  | 1.3.3      |        |
| fof-follow-tags                     | 1.2.6      |        |
| fof-oauth                           | 1.6.11     |        |
| flarum-markdown                     | v1.8.0     |        |
| afrux-forum-widgets-core            | v0.1.7     |        |
| webbinaro-gpx-preview               | 2.0.3      |        |
| webbinaro-calendar                  | 1.7.0      |        |
| v17development-seo                  | v1.8.1     |        |
| sycho-profile-cover                 | v1.3.5     |        |
| nearata-related-discussions         | 1.4.0      |        |
| nearata-no-self-likes               | v1.2.1     |        |
| justoverclock-hot-discussions-cards | 0.1.6      |        |
| ianm-follow-users                   | 1.4.8      |        |
| fof-user-bio                        | 1.4.0      |        |
| fof-terms                           | 1.3.0      |        |
| fof-subscribed                      | 1.1.4      |        |
| fof-split                           | 1.1.1      |        |
| fof-recaptcha                       | 1.3.4      |        |
| fof-reactions                       | 1.4.1      |        |
| fof-profile-image-crop              | 1.1.6      |        |
| fof-pretty-mail                     | 1.1.2      |        |
| fof-polls                           | 2.2.5      |        |
| fof-masquerade                      | 2.1.4      |        |
| fof-links                           | 1.2.3      |        |
| fof-impersonate                     | 1.1.1      |        |
| fof-formatting                      | 1.0.3      |        |
| fof-direct-links                    | 1.0.1      |        |
| fof-default-user-preferences        | 1.2.1      |        |
| fof-byobu                           | 1.3.6      |        |
| fof-best-answer                     | 1.5.3      |        |
| fof-analytics                       | 1.1.0      |        |
| flarum-sticky                       | v1.8.0     |        |
| flarum-statistics                   | v1.8.0     |        |
| flarum-pusher                       | v1.8.0     |        |
| flarum-lock                         | v1.8.0     |        |
| flarum-lang-english                 | v1.8.0     |        |
| flarum-emoji                        | v1.8.0     |        |
| flarum-bbcode                       | v1.8.0     |        |
| dem13n-topic-starter-label          | 0.1.8      |        |
| dem13n-discussion-cards             | 0.3.8      |        |
| clarkwinkelmann-predefined-avatars  | 1.0.1      |        |
| clarkwinkelmann-mailing             | 1.1.0      |        |
| clarkwinkelmann-likes-received      | 1.0.2      |        |
| clarkwinkelmann-group-list          | 1.0.0      |        |
| clarkwinkelmann-email-whitelist     | 1.0.0      |        |
| clarkwinkelmann-circle-groups       | 1.0.1      |        |
| clarkwinkelmann-author-change       | 1.0.3      |        |
| blomstra-welcome-login              | 0.1.0      |        |
| blomstra-digest                     | dev-master |        |
| blomstra-cache-assets               | 0.5        |        |
| askvortsov-rich-text                | v2.1.7     |        |
| askvortsov-categories               | v3.1.0     |        |
| askvortsov-auto-moderator           | v0.1.3     |        |
| afrux-forum-stats-widget            | v0.1.1     |        |
+-------------------------------------+------------+--------+
Base URL: https://adkadv.com
Installation path: /var/www/adkadv.com
Queue driver: sync
Session driver: file
Scheduler status: Active
Mail driver: smtp
Debug mode: off
```

**Possible solution(s)**
Certainly seems like client side JS issue [here](https://github.com/FriendsOfFlarum/upload/blob/master/js/src/common/components/DisplayFile.tsx#L118)

**Additional Context**

The network tab shows a JSON payload properly listing details of all my images.

**Comment by eddiewebb** [comment]
Ah shoot. Must be a way it's interacting with my GPX preview template.  I disabled and things work. Any advice is appreciated, I did follow the wiki for custom templates.

https://github.com/eddiewebb/flarum-gpx-preview/tree/main/js

**Comment by eddiewebb** [comment]
Opened eddiewebb/flarum-gpx-preview#9 to track this

**Comment by eddiewebb** [comment]
Sorry to bother again @imorland - but using the new Template (I was using BB style).   - does that mean I can drop all the JS classes?  Wiki only has PHP code.

eddiewebb/flarum-gpx-preview#10

**Comment by eddiewebb** [comment]
womp womp

```
class Webbinaro\GpxPreview\Templates\GpxTemplate cannot extend interface FoF\Upload\Contracts\Template in /Users/eddie/Development/adk-adv/vendor/webbinaro/gpx-preview/src/Templates/GpxTemplate.php on line 0
````

**Comment by eddiewebb** [comment]
I gave up on the new Template and reverted to useing TextFormatterTemplate.  It works now, but if anyone has advice on how the new template is suppose to return a view I would appreciate it.
